first commit audit
WildCodeSchool/lyon-202109-php-project3-hybride_digital pull request #9
Opened 2021-12-22 08:45 UTC by jcriotte

2021-12-22 13:09 UTC, aldaitzwild requested changes

2021-12-22 13:09 UTC, aldaitzwild commented on src/Controller/AuditController.php
> +    }
What the purpose of this route ?

2021-12-22 13:09 UTC, aldaitzwild commented on templates/audit/index.html.twig
> +								<a href="{{ path('audit_test', {'id': audit.id}) }}">Lancer un test</a>
French or English ! Not both.

2021-12-22 13:09 UTC, aldaitzwild commented on templates/audit/index.html.twig
> +								<a href="{{ path('audit_test', {'id': audit.id}) }}">Lancer un test</a>
Check All files because you the same problems on various templates

2022-01-03 11:02 UTC, jcriotte commented
New version after correction

2022-01-03 14:46 UTC, jcriotte commented
My GIT PUSH didn’t work

2022-01-03 14:50 UTC, aldaitzwild approved these changes

2022-01-03 14:50 UTC, merged